#!/usr/bin/env sh
#MISE description="Run all tests"
#MISE alias=["t"]

set -e

cargo llvm-cov nextest --workspace --summary-only --all-features --no-tests pass
cargo llvm-cov report --html --output-dir coverage
cargo llvm-cov report --cobertura --output-path coverage/cobertura.xml
